---
name: Build - Ubuntu

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        buildtype: [linux-release, linux-debug]
        include:
          - os: ubuntu-18.04
            triplet: x64-linux
          - os: ubuntu-20.04
            triplet: x64-linux
          - os: ubuntu-22.04
            triplet: x64-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Linux Dependencies
        run: > 
          sudo apt-get update && sudo apt-get install python3-setuptools ccache libglew-dev libx11-dev linux-headers-$(uname -r)

      - name: Install Conan
        run: |
          pip install -U pip setuptools 
          pip3 install wheel
          pip3 install conan

      - name: Switch to gcc-11
        run: |
          sudo apt install gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
          sudo update-alternatives --set gcc /usr/bin/gcc-11

      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "1G"
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restore-keys: |
            ccache-${{ matrix.os }}

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Run Conan Install
        run: |
          mkdir build
          cd build
          conan install -s compiler.libcxx=libstdc++11 .. --build=missing

      - name: Run CMake
        run: |
          cd build
          cmake ..

      - name: Compile
        run: |
          cd build
          make -j2

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: otclient-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/otclient
